language: python
dist: xenial
  
python:
  - 3.5
  - 3.6
  - 3.7
  - nightly

matrix:
  include:
    # Python 3.4 not supported in xenial
    - python: 3.4
      dist: trusty
    - env: JOB=HOUSEKEEPING
      python: 3.7
      install:
        - ./bin/fetch-configlet
        - git clone https://github.com/exercism/problem-specifications spec
        - pip install -r requirements-generator.txt
      before_script: ./bin/check-readmes.sh
      script:
        - bin/generate_tests.py --verbose -p spec --check
        # May provide more useful output than configlet fmt
        # if JSON is not valid or items are incomplete
        - ./bin/configlet lint .
        # Verify correct formatting in config.json
        - ./bin/configlet fmt . && git diff --quiet
    - env: JOB=CANONICAL_SYNC
      python: 3.7
      install:
        - pip install requests
        - pip install -r requirements-generator.txt
        - git clone https://github.com/exercism/problem-specifications spec
      before_script: []
      script:
        - echo "Test Version Status" && ./bin/check-test-version.py -p spec
        - echo "Test Template Status" && ./bin/template_status.py -v -p spec
  allow_failures:
    - python: nightly
    - env: JOB=CANONICAL_SYNC

before_script:
  - flake8
  
script: 
  - ./test/check-exercises.py
