language: python
dist: xenial
  
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - nightly

matrix:
  include:
    # Python 3.4 not supported in xenial
    - python: 3.4
      dist: trusty
    - env: JOB=HOUSEKEEPING
      python: 3.7
      install: ./bin/fetch-configlet
      before_script: ./bin/check-readmes.sh
      script:
        # May provide more useful output than configlet fmt
        # if JSON is not valid or items are incomplete
        - ./bin/configlet lint .
        # Verify correct formatting in config.json
        - ./bin/configlet fmt . && git diff --quiet
    - env: JOB=CANONICAL_SYNC
      python: 3.7
      install: git clone https://github.com/exercism/problem-specifications spec
      script: ./bin/check-test-version.py -v -p spec
  allow_failures:
    - python: nightly
    - env: JOB=CANONICAL_SYNC

before_script:
  - flake8
  
script: 
  - ./test/check-exercises.py
