name: Pause Community Contributions

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened
    paths-ignore:
      - 'exercises/*/*/.approaches/**'
      - 'exercises/*/*/.articles/**'

permissions:
  issues: write
  pull-requests: write

jobs:
  pause:
    if: github.repository_owner == 'exercism' # Stops this job from running on forks
    uses: exercism/github-actions/.github/workflows/community-contributions.yml@main
    with:
      forum_category: python
    secrets:
      github_membership_token: ${{ secrets.COMMUNITY_CONTRIBUTIONS_WORKFLOW_TOKEN }}
