name: "Close stale issues"

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 21
          days-before-close: 7

          # Milestones on an issue or a PR exempted from being marked as stale.
          exempt-milestones: true
          # Exempt all issues with milestones from being marked as stale.
          exempt-all-issue-milestones: true

          # Only check issues and PRs with these labels
          any-of-labels: "x:status/claimed,claimed ðŸ¾,dependencies,do not merge ðŸš§,duplicate,experimental ðŸ”¬,
            first-timers only ðŸ£,github_actions,good first issue,good first patch,hacktoberfest ðŸ,
            hacktoberfest-accepted â˜‘,in-progress ðŸŒ¿,invalid,python,security ðŸš¨, wip/content-checking  â˜‘,
            wip/proof-reading ðŸ‘€,wip/story-writing  âœ,wip/style-guideline-checking ðŸ“,spam ðŸš«,status/draft,
            status/wontfix  ðŸ™…ðŸ½"
          stale-issue-label: abandoned ðŸš
          stale-issue-message: >
            This issue has been automatically marked as `abandoned ðŸš`
            because it has not had recent activity. It will be closed if no
            further activity occurs. Thank you
            for your contributions.
          close-issue-message: >
            Closing stale issue. If this issue is still relevant,
            please reopen it.
          stale-pr-label: 'abandoned ðŸš'
          stale-pr-message: >
            This pull request has been automatically marked as `abandoned ðŸš`
            because it has not had recent activity. It will be closed if no
            further activity occurs. Thank you for your contributions.
          close-pr-message: >
            Closing stale pull request. If you are still working on this,
            please reopen this pull request.
